### ISSUE TITLE
Always demands for login information

### ISSUE THREAD

**Issue by ashinzekene** [mykeels/spectranet-cli#1]
Keeps demanding for login information

![image](https://user-images.githubusercontent.com/20991583/46587171-fbdca980-ca7f-11e8-94b3-b5ba584acf55.png)

**Comment by mykeels** [comment]
You can set `SPECTRANET_USERNAME` and `SPECTRANET_PASSWORD` environment variables to persist them

**Comment by ashinzekene** [comment]
It would be nice to set it automatically after the first login

**Comment by mykeels** [comment]
I considered that, then concluded it would be presumptuous.

What if I wanted to login with another user account later? There'd have to be extra command options for that.

**Comment by ashinzekene** [comment]
Well, it's doable :smile:

**Comment by mykeels** [comment]
Yes, it is ... something like 

- `spectranet-cli -u <new-username>` would force the CLI to request for a password, even if credentials are already saved. 

- A `-s` flag could tell the CLI to save the entered credentials in a `.env` file

**Comment by ashinzekene** [comment]
That'd be cool

**Comment by mykeels** [comment]
Are you interested in working on this?

**Comment by ashinzekene** [comment]
So I did this to be able to get how much data I've spent and what's left 

![image](https://user-images.githubusercontent.com/20991583/46732678-13857f00-cc86-11e8-825c-052934e95e63.png)

**Comment by mykeels** [comment]
Oh, awesome ... Does it work even if I'm not on the 10k plan?

**Comment by ladaposamuel** [comment]
can you kindly PR this new feature? @ashinzekene

**Comment by ashinzekene** [comment]
Alright. Would try
